name: Cron
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/5 * * * *"      

jobs:
  cron:
    name: Cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install and run
        env:
          FIGMA_TOKEN: ${{ secrets.figd_BHPdBQLaUH5BsECJN_T8NOhoOX5tSm5_CeAfhP7j }}
          FIGMA_FILE: ${{ secrets.6ibuGlqZtWFJq1IgMpCARu }}
        run: yarn && node app.js

      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Cron'
